sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t pkhot/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true pkhot/react-test npm test

after_success:
  - docker build -t pkhot/multi-client ./client
  - docker build -t pkhot/multi-nginx ./ngnix
  - docker build -t pkhot/multi-server ./server
  - docker build -t pkhot/multi-worker ./worker



